# Generated by Django 4.2.4 on 2023-08-31 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_by', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('updated_by', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('name', models.CharField(db_index=True, help_text='项目名称', max_length=128, verbose_name='项目名称')),
                ('owner', models.CharField(db_index=True, help_text='负责人', max_length=150, verbose_name='负责人')),
                ('project_status', models.PositiveSmallIntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '已完成')], db_index=True, default=1, help_text='项目状态', verbose_name='项目状态')),
                ('members', models.ManyToManyField(blank=True, help_text='项目成员', to=settings.AUTH_USER_MODEL, verbose_name='项目成员')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'pm_project',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_by', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('updated_by', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('name', models.CharField(db_index=True, help_text='迭代名称', max_length=128, verbose_name='迭代名称')),
                ('owner', models.CharField(db_index=True, help_text='负责人', max_length=150, verbose_name='负责人')),
                ('started_at', models.DateTimeField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, help_text='完成时间', null=True, verbose_name='完成时间')),
                ('sprint_status', models.PositiveSmallIntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '已完成')], db_index=True, default=1, help_text='迭代状态', verbose_name='迭代状态')),
                ('project', models.ForeignKey(blank=True, help_text='所属项目', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '迭代',
                'verbose_name_plural': '迭代',
                'db_table': 'pm_sprint',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_by', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('updated_by', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('name', models.CharField(db_index=True, help_text='工作项名称', max_length=128, verbose_name='工作项名称')),
                ('owner', models.CharField(db_index=True, help_text='负责人', max_length=150, verbose_name='负责人')),
                ('work_item_type', models.PositiveSmallIntegerField(choices=[(1, '需求'), (2, '任务'), (3, '缺陷')], db_index=True, help_text='工作项类型', verbose_name='工作项类型')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '最低'), (2, '较低'), (3, '普通'), (4, '较高'), (5, '最高')], db_index=True, help_text='优先级', verbose_name='优先级')),
                ('work_item_status', models.PositiveSmallIntegerField(choices=[(1, '未开始'), (2, '待处理'), (3, '重新打开'), (4, '进行中'), (5, '实现中'), (6, '已完成'), (7, '修复中'), (8, '已实现'), (9, '关闭'), (10, '已修复'), (11, '已验证'), (12, '已拒绝')], db_index=True, default=1, help_text='状态', verbose_name='状态')),
                ('severity', models.PositiveSmallIntegerField(blank=True, choices=[(1, '保留'), (2, '建议'), (3, '提示'), (4, '一般'), (5, '严重'), (6, '致命')], db_index=True, help_text='缺陷严重程度', null=True, verbose_name='缺陷严重程度')),
                ('bug_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, '功能问题'), (2, '性能问题'), (3, '接口问题'), (4, '安全问题'), (5, 'UI界面问题'), (6, '易用性问题'), (7, '兼容问题'), (8, '数据问题'), (9, '逻辑问题'), (10, '需求问题')], db_index=True, help_text='缺陷类型', null=True, verbose_name='缺陷类型')),
                ('process_result', models.PositiveSmallIntegerField(blank=True, choices=[(1, '不予处理'), (2, '延期处理'), (3, '外部原因'), (4, '需求变更'), (5, '转需求'), (6, '挂起'), (7, '设计如此'), (8, '重复缺陷'), (9, '无法重现')], db_index=True, help_text='缺陷处理结果', null=True, verbose_name='缺陷处理结果')),
                ('desc', models.TextField(blank=True, default='', help_text='描述', verbose_name='描述')),
                ('deadline', models.DateTimeField(blank=True, help_text='截止日期', null=True, verbose_name='截止日期')),
                ('followers', models.ManyToManyField(blank=True, help_text='关注人', to=settings.AUTH_USER_MODEL, verbose_name='关注人')),
                ('parent', models.ForeignKey(blank=True, help_text='父工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='父工作项')),
                ('sprint', models.ForeignKey(blank=True, help_text='所属迭代', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.sprint', verbose_name='所属迭代')),
            ],
            options={
                'verbose_name': '工作项',
                'verbose_name_plural': '工作项',
                'db_table': 'pm_work_item',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_by', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('updated_by', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('file', models.FileField(help_text='用户上传的静态文件', upload_to=pm.models.user_directory_path, verbose_name='用户上传的静态文件')),
                ('work_item', models.ForeignKey(blank=True, help_text='所属工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='所属工作项')),
            ],
            options={
                'verbose_name': '静态文件',
                'verbose_name_plural': '静态文件',
                'db_table': 'pm_file',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_by', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('updated_by', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('content', models.TextField(help_text='评论内容', verbose_name='评论内容')),
                ('parent', models.ForeignKey(blank=True, help_text='父评论', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.comment', verbose_name='父评论')),
                ('work_item', models.ForeignKey(blank=True, help_text='所属工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='所属工作项')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'pm_comment',
            },
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('created_by', models.CharField(help_text='创建人', max_length=150, verbose_name='创建人')),
                ('updated_by', models.CharField(help_text='最后修改人', max_length=150, verbose_name='最后修改人')),
                ('changelog', models.JSONField(help_text='变更记录内容', verbose_name='变更记录内容')),
                ('work_item', models.ForeignKey(blank=True, help_text='所属工作项', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pm.workitem', verbose_name='所属工作项')),
            ],
            options={
                'verbose_name': '变更记录',
                'verbose_name_plural': '变更记录',
                'db_table': 'pm_changelog',
            },
        ),
    ]
